name: infra-deployment-pipeline
on:
  push:
    branches:
      - main
      - 'releases/**'

permissions:
  id-token: write    # Required for OIDC
  contents: read     # Required for checkout
jobs:
  infra-deployment-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Terraform
 
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          # Version of terraform to download
          version: 1.13.1
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Terraform Init
        run: terraform init
        working-directory: terraform_envs
      - name: terraform-fmt
        run: terraform fmt
        working-directory: terraform_envs
      - name: terraform-validate
        run: terraform validate
        working-directory: terraform_envs
            

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform_envs

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform_envs
              
