name: Terraform infra workflow

on:
  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  infra-deployment:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Terraform installer
        uses: autero1/action-terraform@v3.0.1
        with:
          # Terraform version to install
          terraform-version: 1.7.5


